### ISSUE TITLE
Download of alpha.v3.zip fails

### ISSUE THREAD

**Issue by quokka-caredx** [DKMS/Hapl-o-Mat#8]
$ python BuildData.py
Download data files
    Download hla_nom_p.txt
    Download hla_nom_g.txt
    Download alpha.v3.zip
Traceback (most recent call last):
  File "BuildData.py", line 99, in <module>
    buildData()
  File "BuildData.py", line 49, in buildData
    DownloadData.downloadAndExtractData()
  File "~/Hapl-o-Mat/prepareData/DownloadData.py", line 46, in downloadAndExtractData
    urlretrieve('https://bioinformatics.bethematchclinical.org/HLA/alpha.v3.zip', filename='alpha.v3.zip')
  File "/usr/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 26181632 out of 30022869 bytes>

**Comment by usolloch** [comment]
In the latest update (Update_EFI2021) we included the possibility to process the necessary data files after manual download. The process is described in the manual (detailedExplanationPrepareData.doc).
